### ISSUE TITLE
Error while running aNMM

### ISSUE THREAD

**Issue by thiziri** [faneshion/MatchZoo#162]
Hi,
While I run aNMM for training I've got the following error:

```
Traceback (most recent call last):  
File "matchzoo/main.py", line 331, in <module>
    main(sys.argv)
  File "matchzoo/main.py", line 323, in main
    train(config)
  File "matchzoo/main.py", line 116, in train
    train_gen[tag] = generator( config = conf )
  File "/MatchZoo/matchzoo/inputs/pair_generator.py", line 306, in __init__
    self.hist_feats[(d1, d2)] = hist_feats[idx]
IndexError: list index out of range
```
I cannot figure out where the problem is, since I've used the same data to run DRMM and it worked without a problem. Is the problem in the computed bins? Here is the log of this model before the error message:
```
{
  "net_name": "anmm",
  "global": {
    "model_type": "PY",
    "weights_file": "../anmm_ranking_bins20_fold_0.weights",
    "save_weights_iters": 10,
    "num_iters": 500,
    "display_interval": 10,
    "test_weights_iters": 100,
    "optimizer": "adam",
    "learning_rate": 0.01
  },
  "inputs": {
    "share": {
      "text1_corpus": "../fold_0/corpus_preprocessed.txt",
      "text2_corpus": "../fold_0/corpus_preprocessed.txt",
      "use_dpool": false,
      "embed_path": "../fold_0/glove_extendStem_300_norm",
      "embed_size": 300,
      "vocab_size": 390811,
      "train_embed": false,
      "target_mode": "ranking",
      "bin_num": 20,
      "text1_maxlen": 10,
      "text2_maxlen": 1000
    },
    "train": {
      "input_type": "DRMM_PairGenerator",
      "phase": "TRAIN",
      "use_iter": false,
      "query_per_iter": 50,
      "batch_per_iter": 10,
      "batch_size": 100,
      "relation_file": "../fold_0/relation_train.txt",
      "hist_feats_file": "../fold_0/relation.train.binsum-20.txt"
    },
    "valid": {
      "input_type": "DRMM_ListGenerator",
      "phase": "EVAL",
      "batch_list": 10,
      "relation_file": "../fold_0/relation_valid.txt",
      "hist_feats_file": "../fold_0/relation.valid.binsum-20.txt"
    },
    "test": {
      "input_type": "DRMM_ListGenerator",
      "phase": "EVAL",
      "batch_list": 10,
      "relation_file": "../fold_0/relation_test.txt",
      "hist_feats_file": "../fold_0/relation.test.binsum-20.txt"
    },
    "predict": {
      "input_type": "DRMM_ListGenerator",
      "phase": "PREDICT",
      "batch_list": 10,
      "relation_file": "../fold_0/relation_test.txt",
      "hist_feats_file": "../fold_0/relation.test.binsum-20.txt"
    }
  },
  "outputs": {
    "predict": {
      "save_format": "TREC",
      "save_path": "../predict.test.anmm_ranking_bins20_fold_0.txt"
    }
  },
  "model": {
    "model_path": "matchzoo/models/",
    "model_py": "anmm.ANMM",
    "setting": {
      "num_layers": 2,
      "hidden_sizes": [
        20,
        1
      ],
      "dropout_rate": 0.0
    }
  },
  "losses": [
    {
      "object_name": "rank_hinge_loss",
      "object_params": {
        "margin": 1.0
      }
    }
  ],
  "metrics": [
    "precision@10",
    "precision@20",
    "ndcg@20",
    "map"
  ]
}
[../fold_0/glove_extendStem_300_norm]
	Embedding size: 390811
Generate numpy embed: %s (390811, 300)
[Embedding] Embedding Load Done.
[Input] Process Input Tags. odict_keys(['train']) in TRAIN, odict_keys(['valid', 'test']) in EVAL.
[../fold_0/corpus_preprocessed.txt]
	Data size: 165996
[Dataset] 1 Dataset Load Done.
{'text1_corpus': '../fold_0/corpus_preprocessed.txt', 'text2_corpus': '../fold_0/corpus_preprocessed.txt', 'use_dpool': False, 'embed_path': '../fold_0/glove_extendStem_300_norm', 'embed_size': 300, 'vocab_size': 390811, 'train_embed': False, 'target_mode': 'ranking', 'bin_num': 20, 'text1_maxlen': 10, 'text2_maxlen': 1000, 'embed': array([[-0.028391, -0.058021,  0.057357, ..., -0.097098, -0.046118,
         0.012638],
       [ 0.007425,  0.107008,  0.039566, ..., -0.00878 ,  0.029111,
        -0.027486],
       [-0.012935,  0.139024,  0.127882, ..., -0.034046, -0.018152,
         0.067485],
       ...,
       [-0.039579,  0.025442, -0.027485, ...,  0.024053,  0.037744,
         0.069247],
       [ 0.114197,  0.005102, -0.011734, ...,  0.093337,  0.039068,
         0.094236],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ]], dtype=float32), 'input_type': 'DRMM_PairGenerator', 'phase': 'TRAIN', 'use_iter': False, 'query_per_iter': 50, 'batch_per_iter': 10, 'batch_size': 100, 'relation_file': '../fold_0/relation_train.txt', 'hist_feats_file': '../fold_0/relation.train.binsum-20.txt'}
[../fold_0/relation_train.txt]
	Instance size: 147396
Pair Instance Count: 7115200
[../fold_0/relation.train.binsum-20.txt]
	Feature size: 32999
```
Thanks for your responses.
@faneshion @bwanglzu @yangliuy

**Comment by thiziri** [comment]
I found in the corresponding line of the code error ([line 306](https://github.com/faneshion/MatchZoo/blob/master/matchzoo/inputs/pair_generator.py#L306)) that it corresponds to the  DRMM_pairGenerator and you defined also other pair_Generators, what's the difference, how the error above could be solved?
Thanks again

**Comment by yangliuy** [comment]
@thiziri in aNMM you  "bin_num" is 20. What is your histogram size in DRMM ? You should make these two setting match. Otherwise, you need to rerun the data preprocess scripts to compute the bin sum with "bin_num=20" before you start the model training process.

**Comment by thiziri** [comment]
Thanks it's solved. 
In fact, I had a problem computing the relation.train.binsum-20.txt, I had less relations then the relation_train.txt. 
Thanks
