### ISSUE TITLE
run MatchZoo/examples/wikiqa$ bash run_mvlstm.sh failed

### ISSUE THREAD

**Issue by loveJasmine** [faneshion/MatchZoo#22]
mldl@mldlUB1604:~/ub16_prj/MatchZoo/examples/wikiqa$ bash run_mvlstm.sh 
Using TensorFlow backend.
2017-12-14 03:37:07.053967: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-14 03:37:07.053990: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-14 03:37:07.054015: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-12-14 03:37:07.054020: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-14 03:37:07.054025: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-12-14 03:37:07.142388: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-12-14 03:37:07.142703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.65GiB
2017-12-14 03:37:07.142718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-12-14 03:37:07.142723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-12-14 03:37:07.142734: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
{
  "inputs": {
    "test": {
      "phase": "EVAL", 
      "input_type": "ListGenerator", 
      "relation_file": "./data/WikiQA/relation_test.txt", 
      "batch_list": 10
    }, 
    "predict": {
      "phase": "PREDICT", 
      "input_type": "ListGenerator", 
      "relation_file": "./data/WikiQA/relation_test.txt", 
      "batch_list": 10
    }, 
    "train": {
      "relation_file": "./data/WikiQA/relation_train.txt", 
      "input_type": "PairGenerator", 
      "batch_size": 100, 
      "batch_per_iter": 5, 
      "phase": "TRAIN", 
      "query_per_iter": 50, 
      "use_iter": false
    }, 
    "share": {
      "vocab_size": 18670, 
      "use_dpool": false, 
      "embed_size": 50, 
      "target_mode": "ranking", 
      "text1_corpus": "./data/WikiQA/corpus_preprocessed.txt", 
      "text2_corpus": "./data/WikiQA/corpus_preprocessed.txt", 
      "embed_path": "./data/WikiQA/embed_glove_d50", 
      "text1_maxlen": 10, 
      "train_embed": false, 
      "text2_maxlen": 40
    }, 
    "valid": {
      "phase": "EVAL", 
      "input_type": "ListGenerator", 
      "relation_file": "./data/WikiQA/relation_valid.txt", 
      "batch_list": 10
    }
  }, 
  "global": {
    "optimizer": "adadelta", 
    "num_iters": 400, 
    "save_weights_iters": 10, 
    "learning_rate": 0.0001, 
    "test_weights_iters": 400, 
    "weights_file": "examples/wikiqa/weights/mvlstm.wikiqa.weights", 
    "model_type": "PY", 
    "display_interval": 10
  }, 
  "outputs": {
    "predict": {
      "save_format": "TREC", 
      "save_path": "predict.test.wikiqa.txt"
    }
  }, 
  "losses": [
    {
      "object_name": "rank_hinge_loss", 
      "object_params": {
        "margin": 1.0
      }
    }
  ], 
  "metrics": [
    "ndcg@3", 
    "ndcg@5", 
    "map"
  ], 
  "net_name": "MVLSTM", 
  "model": {
    "model_py": "mvlstm.MVLSTM", 
    "setting": {
      "dropout_rate": 0.5, 
      "hidden_size": 50, 
      "topk": 100
    }, 
    "model_path": "./matchzoo/models/"
  }
}
[./data/WikiQA/embed_glove_d50]
	Embedding size: 18677
Traceback (most recent call last):
  File "matchzoo/main.py", line 328, in <module>
    main(sys.argv)
  File "matchzoo/main.py", line 320, in main
    train(config)
  File "matchzoo/main.py", line 67, in train
    share_input_conf['embed'] = convert_embed_2_numpy(embed_dict, embed = embed)
  File "/home/mldl/ub16_prj/MatchZoo/matchzoo/utils/rank_io.py", line 93, in convert_embed_2_numpy
    embed[k] = np.array(embed_dict[k])
IndexError: index 18670 is out of bounds for axis 0 with size 18670
mldl@mldlUB1604:~/ub16_prj/MatchZoo/examples/wikiqa$

**Comment by faneshion** [comment]
Are you running the WikiQA dataset? This problem is caused due the vocab_size error in configure file. The 'vocab_size' should be set to the number of lines of word_dict.txt in data directories.

**Comment by loveJasmine** [comment]
new error:

[Model] Model Compile Done.
[12-14-2017 10:19:11]	[Train:train] Traceback (most recent call last):
  File "matchzoo/main.py", line 330, in <module>
    main(sys.argv)
  File "matchzoo/main.py", line 322, in main
    train(config)
  File "matchzoo/main.py", line 151, in train
    verbose = 0
  File "/Users/yike.ke/yike_prj/ve_tf1.0_py2/venv/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
TypeError: fit_generator() got an unexpected keyword argument 'shuffle'

**Comment by faneshion** [comment]
@loveJasmine This problem is due to the version of Keras. You can update it to newer version, or you can juse remove the parameters "shuffle" in fit_generator.

**Comment by loveJasmine** [comment]
yeah！ it works
