### ISSUE TITLE
error running ARCI

### ISSUE THREAD

**Issue by thiziri** [faneshion/MatchZoo#261]
Hi everyone,
I'm running ARCI model in my dataset, I've used the same configuration [you proposed for Quoraqp](https://github.com/faneshion/MatchZoo/blob/master/examples/QuoraQP/config/arci_quoraqp.config)
Here is the configuration file:
```
{
  "net_name": "ARCI",
  "global":{
      "model_type": "PY",
      "weights_file": "./arci_reranking_okapi_fold_0.weights",
      "save_weights_iters": 50,
      "num_iters": 500,
      "display_interval": 10,
      "test_weights_iters": 10,
      "optimizer": "adam",
      "learning_rate": 0.001
  },
  "inputs": {
    "share": {
        "text1_corpus": "./fold_0/corpus_preprocessed.txt",
        "text2_corpus": "./fold_0/corpus_preprocessed.txt",
        "use_dpool": false,
        "embed_size": 300,
        "vocab_size": 468040,
        "train_embed": true,
        "embed_path": "./fold_0/glove_extendStem_300_norm",
        "target_mode": "ranking",
        "text1_maxlen": 10,
        "text2_maxlen": 500
    },
    "train": {
        "input_type": "PairGenerator", 
        "phase": "TRAIN",
        "use_iter": false,
        "query_per_iter": 20,
        "batch_per_iter": 5,
        "batch_size": 32,
        "relation_file": "./fold_0/relation_train.txt"
    },
    "valid": {
        "input_type": "ListGenerator", 
        "phase": "EVAL",
        "batch_list": 10,
        "relation_file": "./fold_0/relation_train.txt"
    },
    "test": {
        "input_type": "ListGenerator", 
        "phase": "EVAL",
        "batch_list": 10,
        "relation_file": "./fold_0/relation_test.txt"
    },
    "predict": {
        "input_type": "ListGenerator", 
        "phase": "PREDICT",
        "batch_list": 10,
        "relation_file": "./fold_0/relation_test.txt"
    }
  },
  "outputs": {
    "predict": {
      "save_format": "TREC",
      "save_path": "./predict_fold_0.test.arci_ranking.txt"
    }
  },
  "model": {
    "model_path": "matchzoo/models/",
    "model_py": "arci.ARCI",
    "setting": {
        "kernel_count": 16,
        "kernel_size": 15,
        "q_pool_size": 15,
        "d_pool_size": 15,
        "dropout_rate": 0.9
    }
  },
  "losses": [ 
    {
       "object_name": "rank_hinge_loss" ,
       "object_params": {
            "margin": 0.5
       }
    }
  ],
  "metrics": [ "precision@20", "ndcg@20", "map" ]
}
```
I've got the following error:
```
Traceback (most recent call last):
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 15 from 10 for 'max_pooling1d_1/MaxPool' (op: 'MaxPool') with input shapes: [?,10,1,16].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "matchzoo/main.py", line 331, in <module>
    main(sys.argv)
  File "matchzoo/main.py", line 323, in main
    train(config)
  File "matchzoo/main.py", line 126, in train
    model = load_model(config)
  File "matchzoo/main.py", line 42, in load_model
    mo = model.build()
  File "matchzoo/models/arci.py", line 56, in build
    q_pool1 = MaxPooling1D(pool_size=self.config['q_pool_size']) (q_conv1)
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/keras/engine/base_layer.py", line 460, in __call__
    output = self.call(inputs, **kwargs)
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/keras/layers/pooling.py", line 46, in call
    data_format='channels_last')
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/keras/layers/pooling.py", line 83, in _pooling_function
    padding, data_format, pool_mode='max')
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 3902, in pool2d
    data_format=tf_data_format)
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 2142, in max_pool
    name=name)
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 4604, in max_pool
    data_format=data_format, name=name)
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/projets/iris/PROJETS/WEIR/python_env/inherited/python3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Negative dimension size caused by subtracting 15 from 10 for 'max_pooling1d_1/MaxPool' (op: 'MaxPool') with input shapes: [?,10,1,16].
```
Could somone give any idea please?
Thanks

**Comment by faneshion** [comment]
You set the 'text1_maxlen'  to 10, while the 'q_pool_size' is 15. Thus, the pool size is larger than the length, which is illegal.

**Comment by mamieterry1** [comment]
How can u tell if your text were taken from your phone remotely

**Comment by thiziri** [comment]
Great, thank you, I could see the difference.
