### ISSUE TITLE
`weights` directory not found

### ISSUE THREAD

**Issue by uduse** [faneshion/MatchZoo#28]
I followed the README.md, cloned the repo and ran `python matchzoo/main.py --phase train --model_file examples/toy_example/config/arci_ranking.config` and this error is shown:

```
Traceback (most recent call last):
  File "matchzoo/main.py", line 328, in <module>
    main(sys.argv)
  File "matchzoo/main.py", line 320, in main
    train(config)
  File "matchzoo/main.py", line 178, in train
    model.save_weights(weights_file % (i_e+1))
  File "/home/zeyi/.virtualenvs/match-zoo/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2586, in save_weights
    f = h5py.File(filepath, 'w')
  File "/home/zeyi/.virtualenvs/match-zoo/local/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/zeyi/.virtualenvs/match-zoo/local/lib/python2.7/site-packages/h5py/_hl/files.py", line 105, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = 'examples/toy_example/weights/arci_ranking.weights.10', errno = 2, error message = 'No such file or directory', flags = 13, o_fla
gs = 242)
```

I resolved this by `mkdir examples/toy_example/weights`. However, this issue needs to be addressed.

There are two possible solutions that comes to my mind:
1. make the directory, and `touch` a `.keep` file, which is the convention of keeping an empty directory in git
2. check `os.path.exists(path)` before saving weights to that directory, if no such path exists, `os.mkdir(path)`

**Comment by faneshion** [comment]
Thanks for your feedback. It's really a good suggestion. We will add it in the next version.
