### ISSUE TITLE
How to train MatchZoo models on very large data sets

### ISSUE THREAD

**Issue by thiziri** [faneshion/MatchZoo#343]
Hi,
I have dataset with a lot of training pairs, when running MatchZoo models for training, I get a following memory error (with RAM 10GO):

>  /usr/local/miniconda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "matchzoo/main_gpu.py", line 351, in <module>
>     main(sys.argv)
>   File "matchzoo/main_gpu.py", line 343, in main
>     train(config, int(args.gpus))
>   File "matchzoo/main_gpu.py", line 117, in train
>     train_gen[tag] = generator( config = conf )
>   File "~/MatchZoo/matchzoo/inputs/pair_generator.py", line 99, in __init__
>     super(PairGenerator, self).__init__(config=config)
>   File "~/MatchZoo/matchzoo/inputs/pair_generator.py", line 25, in __init__
>     self.pair_list = self.make_pair_static(self.rel)
>   File "~/MatchZoo/matchzoo/inputs/pair_generator.py", line 49, in make_pair_static
>     pair_list.append( (d1, high_d2, low_d2) )
> MemoryError 

Here is the running log before this error occures: 
(While running mvlstm):
```
{
  "net_name": "MVLSTM",
  "global": {
    "model_type": "PY",
    "weights_file": "~/MatchZoo/examples/trec_millionQueries/multi_grad_judgement/rerank_2k_okapi/weights/my_models/amvlstm_reranking_okapi_fold_0.weights",
    "save_weights_iters": 50,
    "num_iters": 500,
    "display_interval": 10,
    "test_weights_iters": 300,
    "optimizer": "adadelta",
    "learning_rate": 0.1
  },
  "inputs": {
    "share": {
      "text1_corpus": "~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/corpus_preprocessed.txt",
      "text2_corpus": "~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/corpus_preprocessed.txt",
      "use_dpool": false,
      "embed_size": 300,
      "embed_path": "~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/glove_extendStem_300_norm",
      "vocab_size": 667606,
      "train_embed": false,
      "target_mode": "ranking",
      "text1_maxlen": 10,
      "text2_maxlen": 40
    },
    "train": {
      "input_type": "PairGenerator",
      "phase": "TRAIN",
      "use_iter": false,
      "query_per_iter": 50,
      "batch_per_iter": 5,
      "batch_size": 128,
      "relation_file": "~/MatchZoo_latest/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/relation_train.txt"
    },
    "valid": {
      "input_type": "ListGenerator",
      "phase": "EVAL",
      "batch_list": 10,
      "relation_file": "~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/relation_valid.txt"
    },
    "test": {
      "input_type": "ListGenerator",
      "phase": "EVAL",
      "batch_list": 10,
      "relation_file": "~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/relation_test.txt"
    },
    "predict": {
      "input_type": "ListGenerator",
      "phase": "PREDICT",
      "batch_list": 10,
      "relation_file": "~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/relation_test.txt"
    }
  },
  "outputs": {
    "predict": {
      "save_format": "TREC",
      "save_path": "~/MatchZoo/examples/trec_millionQueries/multi_grad_judgement/rerank_2k_okapi/predictions/predict.test.amvlstm_fold_0.reranking.txt"
    }
  },
  "model": {
    "model_path": "matchzoo/models/",
    "model_py": "mvlstm.MVLSTM",
    "setting": {
      "hidden_size": 50,
      "topk": 100,
      "dropout_rate": 0.5
    }
  },
  "losses": [
    {
      "object_name": "rank_hinge_loss",
      "object_params": {
        "margin": 0.5
      }
    }
  ],
  "metrics": [
    "precision@20",
    "ndcg@20",
    "map"
  ]
}
[~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/glove_extendStem_300_norm]
	Embedding size: 667606
Generate numpy embed: (667606, 300)
[Embedding] Embedding Load Done.
[Input] Process Input Tags. odict_keys(['train']) in TRAIN, odict_keys(['valid', 'test']) in EVAL.
[~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/corpus_preprocessed.txt]
	Data size: 578619
[Dataset] 1 Dataset Load Done.
{'text1_corpus': '~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/corpus_preprocessed.txt', 'text2_corpus': '~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/corpus_preprocessed.txt', 'use_dpool': False, 'embed_size': 300, 'embed_path': '~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/glove_extendStem_300_norm', 'vocab_size': 667606, 'train_embed': False, 'target_mode': 'ranking', 'text1_maxlen': 10, 'text2_maxlen': 40, 'embed': array([[ 0.004176,  0.06535 , -0.033108, ...,  0.068528, -0.0289  ,
        -0.039592],
       [-0.025855, -0.056063, -0.016158, ..., -0.008576,  0.010382,
         0.096152],
       [-0.050733, -0.023928,  0.008703, ..., -0.048408, -0.087827,
         0.066331],
       ...,
       [ 0.100099,  0.030999, -0.053699, ..., -0.003202,  0.089405,
        -0.068456],
       [ 0.037297, -0.046732,  0.007727, ...,  0.112233, -0.03772 ,
        -0.074903],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ]], dtype=float32), 'input_type': 'PairGenerator', 'phase': 'TRAIN', 'use_iter': False, 'query_per_iter': 50, 'batch_per_iter': 5, 'batch_size': 128, 'relation_file': '~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/relation_train.txt'}
[~/data/Robust/train_on_million_queries/multi_graddedJudgements_okapi/rerank_2k_okapi/fold_0/relation_train.txt]
	Instance size: 101405725
```
Thanks in advance
@pl8787 @bwanglzu @faneshion @yangliuy

**Comment by bwanglzu** [comment]
@thiziri which model are u using?

**Comment by bwanglzu** [comment]
@thiziri as discussed before, there is an issue in the `generator`s module in current version of MatchZoo, and seems it's not solvable (and deserve to solve).

The good news is that pair-wise generator has been merged into 2.0 yesterday, see #315 .

W'll have DSSM, acc-i, cdssm available by the end of this week.

**Comment by thiziri** [comment]
Okay, Thanks.
But since I've already a lot of work in progress with the current version, I'm developing my own models with it, running and modifying some other models like MVLSTM, this problem is blocking me. What do you recommend? I feel like being stuck, I'm working with this version for months now.
Is it possible to do the same tasks (developing our own models and/or modifying other models) with the new 2.0 version?

**Comment by bwanglzu** [comment]
@thiziri are you in the wechat group?

**Comment by thiziri** [comment]
No, I've already asked to be added, but still not :(

**Comment by bwanglzu** [comment]
wha'ts your id? I'll invite you.

**Comment by thiziri** [comment]
Hi,
@bwanglzu , since the problem will be solved with the new version of matchzoo, you can close the issue if there are no more comments.
Thanks

**Comment by bwanglzu** [comment]
@thiziri Thanks, I'll do this.
