### ISSUE TITLE
ModuleNotFoundError : No module named 'jieba'

### ISSUE THREAD

**Issue by Joohee-Park** [faneshion/MatchZoo#43]
Hi, first, thank you for your dedication to this library.

I tried to run the script `run_data.sh` and I encountered the following error that wanted me to install 'jieba'. It seems like a Chinese segmentation library, but I don't have any plan to use it for Chinese texts. I wonder if I still have to install jieba, or is there any way to circumvent this issue. Thank you.

```
d3b122:WikiQA$ ./run_data.sh
--2018-01-10 16:17:59--  https://download.microsoft.com/download/E/5/F/E5FCFCEE-7005-4814-853D-DAA7C66507E0/WikiQACorpus.zip
Resolving download.microsoft.com... 23.35.220.223, 2600:140b:4:285::e59, 2600:140b:4:284::e59, ...
Connecting to download.microsoft.com|23.35.220.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7094233 (6.8M) [application/octet-stream]
Saving to: `WikiQACorpus.zip'

100%[=====================================================================================================================================>] 7,094,233   14.7M/s   in 0.5s    

2018-01-10 16:18:00 (14.7 MB/s) - `WikiQACorpus.zip' saved [7094233/7094233]

Archive:  WikiQACorpus.zip
   creating: WikiQACorpus/emnlp-table/
  inflating: WikiQACorpus/emnlp-table/WikiQA.CNN.dev.rank  
  inflating: WikiQACorpus/emnlp-table/WikiQA.CNN.test.rank  
  inflating: WikiQACorpus/emnlp-table/WikiQA.CNN-Cnt.dev.rank  
  inflating: WikiQACorpus/emnlp-table/WikiQA.CNN-Cnt.test.rank  
  inflating: WikiQACorpus/eval.py    
  inflating: WikiQACorpus/Guidelines_Phase1.pdf  
  inflating: WikiQACorpus/Guidelines_Phase2.pdf  
  inflating: WikiQACorpus/WikiQA.tsv  
  inflating: WikiQACorpus/WikiQA-dev.ref  
  inflating: WikiQACorpus/WikiQA-dev.tsv  
  inflating: WikiQACorpus/WikiQA-dev.txt  
  inflating: WikiQACorpus/WikiQA-dev-filtered.ref  
  inflating: WikiQACorpus/WikiQASent.pos.ans.tsv  
  inflating: WikiQACorpus/WikiQA-test.ref  
  inflating: WikiQACorpus/WikiQA-test.tsv  
  inflating: WikiQACorpus/WikiQA-test.txt  
  inflating: WikiQACorpus/WikiQA-test-filtered.ref  
  inflating: WikiQACorpus/WikiQA-train.ref  
  inflating: WikiQACorpus/WikiQA-train.tsv  
  inflating: WikiQACorpus/WikiQA-train.txt  
  inflating: WikiQACorpus/LICENSE.pdf  
  inflating: WikiQACorpus/README.txt  
--2018-01-10 16:18:00--  http://nlp.stanford.edu/data/glove.840B.300d.zip
Resolving nlp.stanford.edu... 171.64.67.140
Connecting to nlp.stanford.edu|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.840B.300d.zip [following]
--2018-01-10 16:18:00--  https://nlp.stanford.edu/data/glove.840B.300d.zip
Connecting to nlp.stanford.edu|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2176768927 (2.0G) [application/zip]
Saving to: `glove.840B.300d.zip'

100%[===================================================================================================================================>] 2,176,768,927  442K/s   in 80m 59s 

2018-01-10 17:39:00 (438 KB/s) - `glove.840B.300d.zip' saved [2176768927/2176768927]

Archive:  glove.840B.300d.zip
  inflating: glove.840B.300d.txt     
--2018-01-10 17:40:09--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu... 171.64.67.140
Connecting to nlp.stanford.edu|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2018-01-10 17:40:09--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: `glove.6B.zip'

100%[=====================================================================================================================================>] 862,182,613  389K/s   in 37m 25s 

2018-01-10 18:17:35 (375 KB/s) - `glove.6B.zip' saved [862182613/862182613]

Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       
Traceback (most recent call last):
  File "prepare_mz_data.py", line 10, in <module>
    from preparation import Preparation
  File "../../matchzoo/inputs/preparation.py", line 11, in <module>
    import preprocess
  File "../../matchzoo/inputs/preprocess.py", line 4, in <module>
    import jieba
ModuleNotFoundError: No module named 'jieba'
load word dict ...
Traceback (most recent call last):
  File "gen_w2v.py", line 126, in <module>
    word_dict = load_word_dict(word_dict_file)
  File "gen_w2v.py", line 107, in load_word_dict
    for line in tqdm(io.open(word_map_file, encoding='utf8')):
FileNotFoundError: [Errno 2] No such file or directory: 'word_dict.txt'
Traceback (most recent call last):
  File "norm_embed.py", line 14, in <module>
    with codecs.open(infile, 'r', encoding='utf8') as f:
  File "/home1/irteam/anaconda3/lib/python3.6/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'embed_glove_d300'
load word dict ...
Traceback (most recent call last):
  File "gen_w2v.py", line 126, in <module>
    word_dict = load_word_dict(word_dict_file)
  File "gen_w2v.py", line 107, in load_word_dict
    for line in tqdm(io.open(word_map_file, encoding='utf8')):
FileNotFoundError: [Errno 2] No such file or directory: 'word_dict.txt'
Traceback (most recent call last):
  File "norm_embed.py", line 14, in <module>
    with codecs.open(infile, 'r', encoding='utf8') as f:
  File "/home1/irteam/anaconda3/lib/python3.6/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'embed_glove_d50'
cat: word_stats.txt: No such file or directory
Traceback (most recent call last):
  File "gen_hist4drmm.py", line 8, in <module>
    from preprocess import cal_hist
  File "../../matchzoo/inputs/preprocess.py", line 4, in <module>
    import jieba
ModuleNotFoundError: No module named 'jieba'
Traceback (most recent call last):
  File "gen_binsum4anmm.py", line 12, in <module>
    from preprocess import cal_binsum
  File "../../matchzoo/inputs/preprocess.py", line 4, in <module>
    import jieba
ModuleNotFoundError: No module named 'jieba'
Done ...
```

**Comment by uduse** [comment]
Just comment it out in the source code if you don't want to use any related functionalities. Installing `jieba` would still be the easist solution, though.

**Comment by o0windseed0o** [comment]
Just use "pip install jieba" for the installation which is a small site package.

**Comment by Joohee-Park** [comment]
Thank you all.

I simply installed jieba and it works well, now.

Xiexie!
