### ISSUE TITLE
训练toy_example的时候出错

### ISSUE THREAD

**Issue by kongliang2015** [faneshion/MatchZoo#48]
训练examples的时候出现错误

执行命令：
python matchzoo/main.py --phase train --model_file examples/toy_example/config/arci_ranking.config

错误信息：
Traceback (most recent call last):
  File "matchzoo/main.py", line 328, in <module>
    main(sys.argv)
  File "matchzoo/main.py", line 320, in main
    train(config)
  File "matchzoo/main.py", line 178, in train
    model.save_weights(weights_file % (i_e+1))
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2586, in save_weights
    f = h5py.File(filepath, 'w')
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 107, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
IOError: Unable to create file (Unable to open file: name = 'examples/toy_example/weights/arci_ranking.weights.10', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)

是这个文件的问题？
examples/toy_example/weights/arci_ranking.weights.10

**Comment by uduse** [comment]
没有 `weights` 文件夹，请参考 #28

**Comment by kongliang2015** [comment]
谢谢！解决了
