### ISSUE TITLE
Error while running gen_hist4drmm.py

### ISSUE THREAD

**Issue by thiziri** [faneshion/MatchZoo#57]
Hi there,
I've computed the different required files following the indications in [data processing](https://github.com/faneshion/MatchZoo/blob/master/data/data%20processing(latter).txt),and due to memory limit, I used the "glove.6B.300d.txt" embeddings. When I run [gen_hist4drmm.py](https://github.com/faneshion/MatchZoo/blob/master/data/WikiQA/gen_hist4drmm.py) with my own data, I've got the following error:

> python gen_hist4drmm.py 60
> [~/MATCHZOO_BASELINES/data/ap88_embed_glove_d300]
> 	Embedding size: 59014
> read embedding finished ...
> Generate numpy embed: %s (59015, 300)
> [~/MATCHZOO_BASELINES/data/corpus_preprocessed.txt]
> 	Data size: 14209
> read corpus finished....
> [~/MATCHZOO_BASELINES/data/relation_train.txt]
> 	Instance size: 13527
> Traceback (most recent call last):
>   File "gen_hist4drmm.py", line 46, in <module>
>     curr_hist = cal_hist(d1_embed, d2_embed, qnum, hist_size)
>   File "../../matchzoo/inputs/preprocess.py", line 433, in cal_hist
>     mhist[i][vid] += 1.
> IndexError: index 77 is out of bounds for axis 0 with size 60

note: I've got the same error with [gen_binsum4anmm.py](https://github.com/faneshion/MatchZoo/blob/master/data/WikiQA/gen_binsum4anmm.py)

Thanks for answering

**Comment by thiziri** [comment]
Hello,
I solved the problem by modifying the following line in [preprocess.py](https://github.com/faneshion/MatchZoo/blob/master/matchzoo/inputs/preprocess.py#L512):
`for inum, did in enumerate(dids):
        fout.write('%s %s %s\n' % (did,str(len(docs[inum])), ' '.join(map(str, docs[inum]))))
  fout.close()`
Because in [corpus_preprocessed.txt](https://github.com/faneshion/MatchZoo/blob/master/data/toy_example/ranking/corpus_preprocessed.txt)  we should have the document length printed in the second column of each document.
Now it's working well.
