### ISSUE TITLE
这行代码会报错……

### ISSUE THREAD

**Issue by guotong1988** [faneshion/MatchZoo#73]
https://github.com/faneshion/MatchZoo/blob/master/matchzoo/models/drmm_tks.py#L56

`mm = Dot(axes=[2, 2], normalize=True)([q_embed, d_embed])`

改成`normalize=False`之后才行

```
Traceback (most recent call last):
  File "/home/gt/MatchZoo/matchzoo/main.py", line 331, in <module>
    main(sys.argv)
  File "/home/gt/MatchZoo/matchzoo/main.py", line 323, in main
    train(config)
  File "/home/gt/MatchZoo/matchzoo/main.py", line 126, in train
    model = load_model(config)
  File "/home/gt/MatchZoo/matchzoo/main.py", line 42, in load_model
    mo = model.build()
  File "/home/gt/MatchZoo/matchzoo/models/drmm_tks.py", line 56, in build
    mm = Dot(axes=[2, 2], normalize=True)([q_embed, d_embed]) # 有改动
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/lib64/python2.7/site-packages/keras/layers/merge.py", line 155, in call
    return self._merge_function(inputs)
  File "/usr/lib64/python2.7/site-packages/keras/layers/merge.py", line 484, in _merge_function
    x1 = K.l2_normalize(x1, axis=axes[0])
  File "/usr/lib64/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3151, in l2_normalize
    return tf.nn.l2_normalize(x, axis=axis)
TypeError: l2_normalize() got an unexpected keyword argument 'axis'
```

**Comment by zhouzhouyang520** [comment]
你是用的GPU吧？我们用GPU的时候也遇到过，这个应该是tensorflow的版本问题

**Comment by guotong1988** [comment]
哦哦，什么版本不报错？，我搞一个~

**Comment by zhouzhouyang520** [comment]
我之前用GPU版本没有问题，被同学不小心改了环境就不行了，现在还在解决中，目测是环境的问题。。。。。

**Comment by luyugao2** [comment]
Keras和TensorFlow的版本不兼容吧，原来TensorFlow只有dim没有axis..

**Comment by guotong1988** [comment]
解决了没……？

**Comment by guotong1988** [comment]
把keras的`tensorflow_backend.py`的l2_normalize改成这样就行了
```
def l2_normalize(x, axis=None):
    return tf.nn.l2_normalize(x, dim=axis)
```
