### ISSUE TITLE
ValueError: Error when checking target: expected dense_1 to have shape (None, 2) but got array with shape (400, 1) if I user PairGenerator

### ISSUE THREAD

**Issue by loveJasmine** [faneshion/MatchZoo#84]
[Model] Model Compile Done.
[04-20-2018 14:58:52]	[Train--:train] on func:make_pair_iter at file:pair_generator.py #61
Traceback (most recent call last):
  File "matchzoo/main.py", line 347, in <module>
    main(sys.argv)
  File "matchzoo/main.py", line 339, in main
    train(config)
  File "matchzoo/main.py", line 166, in train
    verbose = 0
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 2039, in fit_generator
    class_weight=class_weight)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1753, in train_on_batch
    check_batch_axis=True)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1381, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 144, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected dense_1 to have shape (None, 2) but got array with shape (400, 1)

**Comment by loveJasmine** [comment]
use ‘PairGenerator' in train will cause this error,
however
I can fix it by change ‘categorical_crossentropy’ to ‘sparse_categorical_crossentropy'
